## Sử dụng .loc
Phương thức `.loc` dùng để lấy dữ liệu theo cột hoặc hàng dựa theo nhãn định sẵn (Tên hàng, tên cột), ngoài ra `.loc` còn nhận các giá trị boolean.

Đầu vào của `.loc` có thể gồm:

- Nhãn đơn: là 1 số `3` hoặc dạng chữ `a`, lưu ý rằng số này là nhãn của `index` chứ không phải vị trí của dòng.

- Danh sách các nhãn : `['a', 'b', 'c']`

- Đối tượng dạng slice ví dụ `'a':'e'`

- Danh sách kiểu `bool` có độ dài bằng với số lượng dòng

- `Series` dạng `bool`

- `pd.Index`



Sử dụng nhãn đơn, kết quả trả về là các dòng có nhãn giống như nhãn trong `.loc`

```python
df.loc['Pacific']
```

```{.python_output}          
              state  individuals  family_members  state_pop
region                                                     
Pacific      Alaska       1434.0           582.0     735139
Pacific  California     109008.0         20964.0   39461588
```
```{block2, type='rmdnote'}
**_Lưu ý:_** 

Khi kết quả là nhiều dòng thì dữ liệu trả về có kiểu `DataFrame`, trong khi nếu chỉ có 1 dòng duy nhất thì kết quả trả về sẽ theo kiểu `Series`
``` 

```python
type(df.loc['Pacific'])
```

```{.python_output}
<class 'pandas.core.frame.DataFrame'>
```

```python
type(df.loc['West South Central'])
```

```{.python_output} 
<class 'pandas.core.series.Series'>
```

Khi đưa danh sách các nhãn dùng `.loc[[]]` thì nhãn đưa vào là nhãn của `index`. Nếu đưa tên các cột sẽ bị báo lỗi `KeyError`

```python
df.loc[['Pacific', 'Mountain']]
```

```{.python_output}
               state  individuals  family_members  state_pop
region                                                      
Pacific       Alaska       1434.0           582.0     735139
Pacific   California     109008.0         20964.0   39461588
Mountain     Arizona       7259.0          2606.0    7158024
Mountain    Colorado       7607.0          3250.0    5691287
```

Để lấy nhãn đơn theo nhãn của `index` và tên `column` ta truyền vào phần nhãn của `index` trước và nhãn của `column` sau và phân biệt bởi dấu phẩy

```python
df.loc['Pacific', 'state']
```

```{.python_output}
region
Pacific        Alaska
Pacific    California
Name: state, dtype: object
```

Để lấy nhiều hơn 1 nhãn của `index` hoặc nhiều hơn 1 nhãn của `column` ta chỉ cần thay thế nhãn đơn của `index` thành danh sách hoặc slice, tương tự ta có thế thay thế nhãn đơn thành danh sách hoặc slice của `column`

```python
df.loc['Pacific', ['individuals', 'family_members']])
```

```{.python_output}
         individuals  family_members
region                              
Pacific       1434.0           582.0
Pacific     109008.0         20964.0
```

```python
df.loc['Pacific', 'individuals':'state_pop']
```

```{.python_output}
         individuals  family_members  state_pop
region                                         
Pacific       1434.0           582.0     735139
Pacific     109008.0         20964.0   39461588
```

```{block2, type='rmdnote'}
**_Lưu ý:_** 

- Dùng slice sẽ lấy theo thứ tự xuất hiện chứ không lấy theo thứ tự sắp xếp từ điển, như ví dụ trên thì mặc dù `family_members` > `individuals` nhưng vẫn xếp sau.

- Slice không áp dụng được cho `index` có nhãn trùng nhau, nếu dùng sẽ báo lỗi `KeyError: "Cannot get right slice bound for non-unique label:`
``` 

Danh sách dạng `boolean`, chỉ sử dụng cho `index`, không dùng cho `column`

```python
df.loc[[False, True, False, True, False, False]]
```

```{.python_output}
                       state  individuals  family_members  state_pop
region                                                              
Pacific               Alaska       1434.0           582.0     735139
West South Central  Arkansas       2280.0           432.0    3009733
```

Series boolean
```python
s = pd.Series([False, True, False, True, False, False],
              index=['East South Central', 'Pacific', 'Mountain', 'West South Central', 'Pacific', 'Mountain'])
df.loc[s]
```

```{.python_output}
                       state  individuals  family_members  state_pop
region                                                              
Pacific               Alaska       1434.0           582.0     735139
West South Central  Arkansas       2280.0           432.0    3009733
```

`pd.Index`

```python
df.loc[pd.Index(["Pacific", "East South Central"], name="meow")]
```

```{.python_output}
                         state  individuals  family_members  state_pop
meow                                                                   
Pacific                 Alaska       1434.0           582.0     735139
Pacific             California     109008.0         20964.0   39461588
East South Central     Alabama       2570.0           864.0    4887681
```

**Select với `MultiIndex`**
```python
                     individuals  family_members  state_pop
region   state                                             
Mountain Arizona          7259.0          2606.0    7158024
         Colorado         7607.0          3250.0    5691287
         Idaho            1297.0           715.0    1750536
Pacific  Alaska           1434.0           582.0     735139
         California     109008.0         20964.0   39461588
         Hawaii           4131.0          2399.0    1420593
```

Với nhãn đơn

```python
df.loc['Mountain']
```

```{.python_output} 
          individuals  family_members  state_pop
state                                           
Arizona        7259.0          2606.0    7158024
Colorado       7607.0          3250.0    5691287
Idaho          1297.0           715.0    1750536
```

```{block2, type='rmdnote'}
**_Lưu ý:_** 
Với `MultiIndex`,các index sẽ xếp theo thứ tự từ level 0 đến n (`level 0` cao hơn `level 1` ...),  với nhãn đơn là nhãn của 1 `index` thì chỉ thực hiện được index level đầu tiên, các index level sau sẽ báo lỗi.
Theo như ví dụ trên thì `region` có level cao hơn 'state' nên chỉ gọi được `.loc['Mountain']` còn `.loc['Arizona']` sẽ báo lỗi
``` 

Để select nhiều index cùng lúc, ta truyền vào `tuple(label1, label2...)` theo thứ tự index có level từ cao đến thấp

```python
df.loc[('Mountain', 'Colorado')]
```

```{.python_output}
individuals          7607.0
family_members       3250.0
state_pop         5691287.0
Name: (Mountain, Colorado), dtype: float64
```

Tương tự ta cùng có select theo các column cho trước

```python
df.loc[('Mountain', 'Colorado'), ['individuals', 'family_members']]
```

```{.python_output}
individuals       7607.0
family_members    3250.0
Name: (Mountain, Colorado), dtype: float64
```

```{block2, type='rmdtip'}
**_Mẹo:_**
Có thể select `index` ở các level sau bằng cách dùng `slice`

```

```python
df.loc[(slice(None), 'Arizona'), :]
```

```{.python_output}
                  individuals  family_members  state_pop
region   state                                          
Mountain Arizona       7259.0          2606.0    7158024
```

**Slice cho MultiIndex**

Slice từ 1 tuple nhãn đến một nhãn đơn

```python
df.loc[('Mountain', 'Colorado'):'Pacific']
```

```{.python_output}
                     individuals  family_members  state_pop
region   state                                             
Mountain Colorado         7607.0          3250.0    5691287
         Idaho            1297.0           715.0    1750536
Pacific  Alaska           1434.0           582.0     735139
         California     109008.0         20964.0   39461588
         Hawaii           4131.0          2399.0    1420593
```

```{block2, type='rmdnote'}
**_Lưu ý:_** 
Nhãn đơn phía sau phải có cùng level với nhãn đầu tiên trong tuple. Trong ví dụ trên nếu thay `Pacific` thành `Hawaii` sẽ trả về rỗng. Nhưng khi truyền nhãn không nằm trong các nhãn của index thì vẫn có kết quả trả về
``` 

```python
df.loc[('Mountain', 'Colorado'): 'meow']
```

```{.python_output}
                     individuals  family_members  state_pop
region   state                                             
Mountain Colorado         7607.0          3250.0    5691287
         Idaho            1297.0           715.0    1750536
Pacific  Alaska           1434.0           582.0     735139
         California     109008.0         20964.0   39461588
         Hawaii           4131.0          2399.0    1420593
```

Slice từ 1 tuple nhãn đến một tuple nhãn

```python
df.loc[('Mountain', 'Colorado'):('Pacific', 'California')]
```

```{.python_output}
                     individuals  family_members  state_pop
region   state                                             
Mountain Colorado         7607.0          3250.0    5691287
         Idaho            1297.0           715.0    1750536
Pacific  Alaska           1434.0           582.0     735139
         California     109008.0         20964.0   39461588
```